on:
  workflow_dispatch:
  schedule:
    # run everyday at midnight
    - cron: '0 0 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: notPlancha/Scoop-Github-Actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '0'
          THROW_ERROR: '1'
